#!/bin/bash
MOTD="Welcome to Prometheus manager v4.0.1!"

# Set default values
SYSTEM_ARCH=amd64 # -> can be changed by script argument --arch arm64

LOG_LEVEL=0

DEBUG_OFFLINE=false

NODE_TRIGGER=false
BLACKBOX_TRIGGER=false
ALERTMANAGER_TRIGGER=false
PROMETHEUS_TRIGGER=false
SHELL2HTTP_TRIGGER=false
PINGME_TRIGGER=false

DISPLAY_VERSIONS=false

UPDATE_VERSIONS=false
UPDATE_CONFIGS=false
INSTALL=false

# Default configuration if not override by .env file
NODE_EXPORTER_PORT=9500
BLACKBOX_EXPORTER_PORT=9510
ALERTMANAGER_PORT=9550
SHELL2HTTP_PORT=9560
PROMETHEUS_PORT=9590

EXECUTE=false
KILL_APPS=false
STATUS_APPS=false

REMOVE_APPS=false

function usage {
        echo "Usage: $(basename "$0") [<flags>]" 2>&1
        echo '   -h, --help                          Show this help context'
        echo '   -v, --verbose                       Adaptative verbose mode (-vv for WARN,'
        echo '                                       -vvv for INFO, -vvvv for full debugging)'
        echo '   --arch arm64                        Set architecture, default is amd64'
        echo '   --list-ports                        List all ports actually used'
        echo '   -V, --versions [--<all|apps>]       Display versions for selected apps'
        echo '                                       e.g. --all | --node | --cgi | etc.'
        echo '                                       (see additional flags below)'
        echo '   --update-versions [--<all|apps>]    Retrieve last version numbers available'
        echo '                                       for selected apps'
        echo '   -i, --install [--<all|apps>]        Install selected apps'
        echo '   -e, --exec [--<all|apps>]           Execute selected apps'
        echo '   -s, --status [--<all|apps>]         Prompt selected apps status'
        echo '   -k, --kill [--<all|apps>]           Stop selected apps daemons'
        echo '   --remove [--<all|apps>]             Remove all data, users and services for'
        echo '                                       selected apps'
        echo '   --update-config                     Overwrite config files based on .env'
        echo '                                       file and alerts config (need restart)'
        echo '   --offline                           For debug purpose only'
        echo ''
        echo '------------- APPS FLAGS -----------------------------------------------------'
        echo ''
        echo '   --all                               Process script for all available apps'
        echo '                                       (prometheus, node_exporter, etc.)'
        echo '   -n, --node, -N [<version>]          Process for node_exporter'
        echo '                                       Version can be forced with capital letter'
        echo '   -b, --blackbox, -B [<version>]      Process for blackbox_exporter'
        echo '   -a, --alertmanager, -A [<version>]  Process for Alertmanager'
        echo '   -p, --prometheus, -P [<version>]    Process for Prometheus'
        echo '   -c, --cgi, -C [<version>]           Process for CGI SHELL2HTTP API'
        echo '   -m, --messaging, -M [<version>]     Process for Messaging System (PingMe CLI)'
        exit 1
}


function flags() {
  while [[ $# -gt 0 ]]; do
    case $1 in
      -h|--help)
        usage
        exit 1
        ;;
      -v|--verbose)
        LOG_LEVEL=1
        shift # argument
        ;;
      -vv)
        LOG_LEVEL=2
        shift # argument
        ;;
      -vvv)
        LOG_LEVEL=3
        shift # argument
        ;;
      -vvvv)
        LOG_LEVEL=4
        shift # argument
        ;;
      -V|--versions)
        DISPLAY_VERSIONS=true
        shift # argument
        ;;
      --update-versions)
        UPDATE_VERSIONS=true
        shift # argument
        ;;
      --update-config)
        UPDATE_CONFIGS=true
        shift # argument
        ;;
      -i|--install)
        INSTALL=true
        shift # argument
        ;;
      -e|--exec)
        EXECUTE=true
        shift # argument
        ;;
      -s|--status)
        STATUS_APPS=true
        shift # argument
        ;;
      -k|--kill)
        KILL_APPS=true
        shift # argument
        ;;
      --remove)
        KILL_APPS=true
        REMOVE_APPS=true
        shift # argument
        ;;
      --all)
        NODE_TRIGGER=true
        BLACKBOX_TRIGGER=true
        PROMETHEUS_TRIGGER=true
        ALERTMANAGER_TRIGGER=true
        SHELL2HTTP_TRIGGER=true
        PINGME_TRIGGER=true
        shift # argument
        ;;
      -n|--node)
        NODE_TRIGGER=true
        shift # argument
        ;;
      -N)
        check_options_mandatory "$2"
        NODE_EXPORTER_VERSION="$2"
        NODE_TRIGGER=true
        shift # argument
        shift # value
        ;;
      -b|--blackbox)
        BLACKBOX_TRIGGER=true
        shift # argument
        ;;
      -B)
        check_options_mandatory "$2"
        BLACKBOX_EXPORTER_VERSION="$2"
        BLACKBOX_TRIGGER=true
        shift # argument
        shift # value
        ;;
      -a|--alertmanager)
        ALERTMANAGER_TRIGGER=true
        shift # argument
        ;;
      -A)
        check_options_mandatory "$2"
        ALERTMANAGER_VERSION="$2"
        ALERTMANAGER_TRIGGER=true
        shift # argument
        shift # value
        ;;
      -p|--prometheus)
        PROMETHEUS_TRIGGER=true
        shift # argument
        ;;
      -P)
        check_options_mandatory "$2"
        PROMETHEUS_VERSION="$2"
        PROMETHEUS_TRIGGER=true
        shift # argument
        shift # value
        ;;
      -c|--cgi)
        SHELL2HTTP_TRIGGER=true
        PINGME_TRIGGER=true
        shift # argument
        ;;
      -C)
        check_options_mandatory "$2"
        SHELL2HTTP_VERSION="$2"
        SHELL2HTTP_TRIGGER=true
        PINGME_TRIGGER=true
        shift # argument
        shift # value
        ;;
      -m|--messaging)
        PINGME_TRIGGER=true
        SHELL2HTTP_TRIGGER=true
        shift # argument
        ;;
      -M)
        check_options_mandatory "$2"
        PINGME_VERSION="$2"
        PINGME_TRIGGER=true
        SHELL2HTTP_TRIGGER=true
        shift # argument
        shift # value
        ;;
      --list-ports)
        list_used_ports
        shift # argument
        ;;
      --arch)
        check_options_mandatory "$2"
        SYSTEM_ARCH="$2"
        shift # argument
        shift # value
        ;;
      --offline)
        DEBUG_OFFLINE=true
        shift # argument
        ;;
      -*|--*)
        echo "Unknown option $1"
        exit 1
        ;;
      *)
        POSITIONAL_ARGS+=("$1") # save positional arg
        shift # past argument
        ;;
    esac
  done
}


function check_options_mandatory() {
    if [ "${1::1}" == "-" ]
    then
      echo "Value is mandatory for argument before $1"
      exit 1
    fi

    if [ -z "$1" ]
    then
      echo "Value is mandatory for final argument"
      exit 1
    fi
}


function check_root_rights(){
  if [ "$(id -u)" -ne 0 ]
  then
    echo "[ERROR] This script require sudo rights to run smoothly"
  fi
}


function retrieve_node_version() {
    if [ $LOG_LEVEL -gt 3 ]
    then
      echo '[DEBUG] Retrieving node_exporter version...'
    fi
    NODE_EXPORTER_VERSION_CURLED="$(curl -s https://api.github.com/repos/prometheus/node_exporter/releases/latest |
    grep 'tag_name' | awk '{printf substr($2, 3, length($2)-4)}')"

    if [[ -z $NODE_EXPORTER_VERSION_CURLED ]]
    then
      echo '[ERROR] System was not able to retrieve node_exporter version check your internet connection'
      exit 1
    fi

    if [ $LOG_LEVEL -gt 2 ]
    then
      echo "[INFO] node_exporter version retrieved: " "$NODE_EXPORTER_VERSION_CURLED"
    fi
}


function retrieve_blackbox_version() {
    if [ $LOG_LEVEL -gt 3 ]
    then
      echo '[DEBUG] Retrieving blackbox_exporter version...'
    fi
    BLACKBOX_EXPORTER_VERSION_CURLED="$(curl -s https://api.github.com/repos/prometheus/blackbox_exporter/releases/latest |
    grep 'tag_name' | awk '{printf substr($2, 3, length($2)-4)}')"

    if [[ -z $BLACKBOX_EXPORTER_VERSION_CURLED ]]
    then
      echo '[ERROR] System was not able to retrieve blackbox_exporter version check your internet connection'
      exit 1
    fi

    if [ $LOG_LEVEL -gt 2 ]
    then
      echo "[INFO] blackbox_exporter version retrieved: " "$BLACKBOX_EXPORTER_VERSION_CURLED"
    fi
}


function retrieve_alertmanager_version() {
    if [ $LOG_LEVEL -gt 3 ]
    then
      echo '[DEBUG] Retrieving alertmanager version...'
    fi
    ALERTMANAGER_VERSION_CURLED="$(curl -s https://api.github.com/repos/prometheus/alertmanager/releases/latest |
    grep 'tag_name' | awk '{printf substr($2, 3, length($2)-4)}')"

    if [[ -z $ALERTMANAGER_VERSION_CURLED ]]
    then
      echo '[ERROR] System was not able to retrieve alertmanager version check your internet connection'
      exit 1
    fi

    if [ $LOG_LEVEL -gt 2 ]
    then
      echo "[INFO] alertmanager version retrieved: " "$ALERTMANAGER_VERSION_CURLED"
    fi
}


function retrieve_shell2http_version() {
    if [ $LOG_LEVEL -gt 3 ]
    then
      echo '[DEBUG] Retrieving shell2http version...'
    fi

    SHELL2HTTP_VERSION_CURLED="$(curl -s https://api.github.com/repos/msoap/shell2http/releases/latest |
    grep 'tag_name' | awk '{printf substr($2, 3, length($2)-4)}')"

    if [[ -z $SHELL2HTTP_VERSION_CURLED ]]
    then
      echo '[ERROR] System was not able to retrieve shell2http version check your internet connection'
      exit 1
    fi

    if [ $LOG_LEVEL -gt 2 ]
    then
      echo "[INFO] shell2http version retrieved: " "$SHELL2HTTP_VERSION_CURLED"
    fi
}


function retrieve_pingme_version() {
    if [ $LOG_LEVEL -gt 3 ]
    then
      echo '[DEBUG] Retrieving PingMe CLI version...'
    fi

    PINGME_VERSION_CURLED="$(curl -s https://api.github.com/repos/kha7iq/pingme/releases/latest |
    grep 'tag_name' | awk '{printf substr($2, 3, length($2)-4)}')"

    if [[ -z $PINGME_VERSION_CURLED ]]
    then
      echo '[ERROR] System was not able to retrieve PingMe CLI version check your internet connection'
      exit 1
    fi

    if [ $LOG_LEVEL -gt 2 ]
    then
      echo "[INFO] PingMe CLI version retrieved: " "$PINGME_VERSION_CURLED"
    fi
}


function retrieve_prometheus_version() {
    if [ $LOG_LEVEL -gt 3 ]
    then
      echo '[DEBUG] Retrieving prometheus version...'
    fi
    PROMETHEUS_VERSION_CURLED="$(curl -s https://api.github.com/repos/prometheus/prometheus/releases/latest |
    grep 'tag_name' | awk '{printf substr($2, 3, length($2)-4)}')"

    if [[ -z $PROMETHEUS_VERSION_CURLED ]]
    then
      echo '[ERROR] System was not able to retrieve prometheus version check your internet connection'
      exit 1
    fi

    if [ $LOG_LEVEL -gt 2 ]
    then
      echo "[INFO] prometheus version retrieved: " "$PROMETHEUS_VERSION_CURLED"
    fi
}


function ensure_versions() {
  if [ $LOG_LEVEL -gt 3 ]; then printf "[DEBUG] UPDATE_VERSIONS flag is: %s\n" "$UPDATE_VERSIONS"; fi

  # Test if file is correctly filled or if update is request
  if $NODE_TRIGGER && $UPDATE_VERSIONS || [ "${#NODE_EXPORTER_VERSION}" -lt 5 ]
  then
    retrieve_node_version
    NODE_EXPORTER_VERSION=$NODE_EXPORTER_VERSION_CURLED
  fi

  if $BLACKBOX_TRIGGER && $UPDATE_VERSIONS || [ "${#BLACKBOX_EXPORTER_VERSION}" -lt 5 ]
  then
    retrieve_blackbox_version
    BLACKBOX_EXPORTER_VERSION=$BLACKBOX_EXPORTER_VERSION_CURLED
  fi

  if $ALERTMANAGER_TRIGGER && $UPDATE_VERSIONS || [ "${#ALERTMANAGER_VERSION}" -lt 5 ]
  then
    retrieve_alertmanager_version
    ALERTMANAGER_VERSION=$ALERTMANAGER_VERSION_CURLED
  fi

  if $SHELL2HTTP_TRIGGER && $UPDATE_VERSIONS || [ "${#SHELL2HTTP_VERSION}" -lt 5 ]
  then
    retrieve_shell2http_version
    SHELL2HTTP_VERSION=$SHELL2HTTP_VERSION_CURLED
  fi

  if $PINGME_TRIGGER && $UPDATE_VERSIONS || [ "${#PINGME_VERSION}" -lt 5 ]
  then
    retrieve_pingme_version
    PINGME_VERSION=$PINGME_VERSION_CURLED
  fi

  if $PROMETHEUS_TRIGGER && $UPDATE_VERSIONS || [ "${#PROMETHEUS_VERSION}" -lt 5 ]
  then
    retrieve_prometheus_version
    PROMETHEUS_VERSION=$PROMETHEUS_VERSION_CURLED
  fi
}


function store_actual_versions() {
  if [ $LOG_LEVEL -gt 3 ]; then echo '[DEBUG] Storing new versions in .versions file...'; fi
  cat > .versions << EOM
NODE_EXPORTER_VERSION=$NODE_EXPORTER_VERSION
BLACKBOX_EXPORTER_VERSION=$BLACKBOX_EXPORTER_VERSION
ALERTMANAGER_VERSION=$ALERTMANAGER_VERSION
PROMETHEUS_VERSION=$PROMETHEUS_VERSION
SHELL2HTTP_VERSION=$SHELL2HTTP_VERSION
PINGME_VERSION=$PINGME_VERSION
EOM

  chmod 666 .versions
  if [ $LOG_LEVEL -gt 2 ]; then echo '[INFO] Versions stored locally'; fi
}


function update_versions() {
  ensure_versions
  store_actual_versions
}


function display_node_versions() {
  if $DEBUG_OFFLINE; then NODE_EXPORTER_VERSION_CURLED=""; else retrieve_node_version; fi
  if [ -z "$NODE_EXPORTER_VERSION_CURLED" ]
  then
    NODE_EXPORTER_VERSION_CURLED="You're offline"
  fi
  printf "Highest available version for node_exporter is: %s\n" "$NODE_EXPORTER_VERSION_CURLED"

  printf "Installation version for node_exporter will be: %s\n" "$NODE_EXPORTER_VERSION"

  INSTALLED_NODE_EXPORTER_VERSION=$(/usr/local/bin/node_exporter --version 2>&1 | awk 'NR==1 {printf $3}')
  if [ "${#INSTALLED_NODE_EXPORTER_VERSION}" -lt 5 ]
  then
    INSTALLED_NODE_EXPORTER_VERSION="Not installed"
  fi
  printf "Actual version of node_exporter is: %s\n\n" "$INSTALLED_NODE_EXPORTER_VERSION"
}


function display_blackbox_versions() {
  if $DEBUG_OFFLINE; then BLACKBOX_EXPORTER_VERSION_CURLED=""; else retrieve_blackbox_version; fi
  if [ -z "$BLACKBOX_EXPORTER_VERSION_CURLED" ]
  then
    BLACKBOX_EXPORTER_VERSION_CURLED="You're offline"
  fi
  printf "Highest available version for blackbox_exporter is: %s\n" "$BLACKBOX_EXPORTER_VERSION_CURLED"

  printf "Installation version for blackbox_exporter will be: %s\n" "$BLACKBOX_EXPORTER_VERSION"

  INSTALLED_BLACKBOX_EXPORTER_VERSION=$(/usr/local/bin/blackbox_exporter --version 2>&1 | awk 'NR==1 {printf $3}')
  if [ "${#INSTALLED_BLACKBOX_EXPORTER_VERSION}" -lt 5 ]
  then
    INSTALLED_BLACKBOX_EXPORTER_VERSION="Not installed"
  fi
  printf "Actual version of blackbox_exporter is: %s\n\n" "$INSTALLED_BLACKBOX_EXPORTER_VERSION"
}


function display_alertmanager_versions() {
  if $DEBUG_OFFLINE; then ALERTMANAGER_VERSION_CURLED=""; else retrieve_alertmanager_version; fi
  if [ -z "$ALERTMANAGER_VERSION_CURLED" ]
  then
    ALERTMANAGER_VERSION_CURLED="You're offline"
  fi
  printf "Highest available version for alertmanager is: %s\n" "$ALERTMANAGER_VERSION_CURLED"

  printf "Installation version for alertmanager will be: %s\n" "$ALERTMANAGER_VERSION"

  INSTALLED_ALERTMANAGER_VERSION=$(/usr/local/bin/alertmanager --version 2>&1 | awk 'NR==1 {printf $3}')
  if [ "${#INSTALLED_ALERTMANAGER_VERSION}" -lt 5 ]
  then
    INSTALLED_ALERTMANAGER_VERSION="Not installed"
  fi
  printf "Actual version of alertmanager is: %s\n\n" "$INSTALLED_ALERTMANAGER_VERSION"
}


function display_shell2http_versions() {
  if $DEBUG_OFFLINE; then SHELL2HTTP_VERSION_CURLED=""; else retrieve_shell2http_version; fi
  if [ -z "$SHELL2HTTP_VERSION_CURLED" ]
  then
    SHELL2HTTP_VERSION_CURLED="You're offline"
  fi
  printf "Highest available version for shell2http is: %s\n" "$SHELL2HTTP_VERSION_CURLED"

  printf "Installation version for shell2http will be: %s\n" "$SHELL2HTTP_VERSION"

  INSTALLED_SHELL2HTTP_VERSION=$(/usr/local/bin/shell2http --version 2>&1)
  if [ "${#INSTALLED_SHELL2HTTP_VERSION}" -lt 5 ]
  then
    INSTALLED_SHELL2HTTP_VERSION="Not installed"
  fi
  printf "Actual version of shell2http is: %s\n\n" "$INSTALLED_SHELL2HTTP_VERSION"
}


function display_pingme_versions() {
  if $DEBUG_OFFLINE; then PINGME_VERSION_CURLED=""; else retrieve_pingme_version; fi
  if [ -z "$PINGME_VERSION_CURLED" ]
  then
    PINGME_VERSION_CURLED="You're offline"
  fi
  printf "Highest available version for PingMe CLI is: %s\n" "$PINGME_VERSION_CURLED"

  printf "Installation version for PingMe CLI will be: %s\n" "$PINGME_VERSION"

  INSTALLED_PINGME_VERSION=$(/usr/local/bin/pingme --version 2>&1 | awk 'NR==1 {printf $3}')
  if [ "${#INSTALLED_PINGME_VERSION}" -lt 5 ]
  then
    INSTALLED_PINGME_VERSION="Not installed"
  fi
  printf "Actual version of PingMe CLI is: %s\n\n" "$INSTALLED_PINGME_VERSION"
}


function display_prometheus_versions() {
  if $DEBUG_OFFLINE; then PROMETHEUS_VERSION_CURLED=""; else retrieve_prometheus_version; fi
  if [ -z "$PROMETHEUS_VERSION_CURLED" ]
  then
    PROMETHEUS_VERSION_CURLED="You're offline"
  fi
  printf "Highest available version for Prometheus is: %s\n" "$PROMETHEUS_VERSION_CURLED"

  printf "Installation version for Prometheus will be: %s\n" "$PROMETHEUS_VERSION"

  INSTALLED_PROMETHEUS_VERSION=$(/usr/local/bin/prometheus --version 2>&1 | awk 'NR==1 {printf $3}')
  if [ "${#INSTALLED_PROMETHEUS_VERSION}" -lt 5 ]
  then
    INSTALLED_PROMETHEUS_VERSION="Not installed"
  fi
  printf "Actual version of prometheus is: %s\n\n" "$INSTALLED_PROMETHEUS_VERSION"
  test -f /usr/local/bin/promtool && printf "Promtool is present\n"
}


function display_versions() {
  if $NODE_TRIGGER; then display_node_versions; fi
  if $BLACKBOX_TRIGGER; then display_blackbox_versions; fi
  if $ALERTMANAGER_TRIGGER; then display_alertmanager_versions; fi
  if $SHELL2HTTP_TRIGGER; then display_shell2http_versions; fi
  if $PINGME_TRIGGER; then display_pingme_versions; fi
  if $PROMETHEUS_TRIGGER; then display_prometheus_versions; fi
}


function download_node_exporter() {
  if [ $LOG_LEVEL -gt 2 ]; then printf "[INFO] Download node_exporter\n"; fi
  useradd --no-create-home --shell /bin/false node_exporter &> /dev/null || grep node_exporter /etc/passwd
  test -f node_exporter-"$NODE_EXPORTER_VERSION".linux-"$SYSTEM_ARCH".tar.gz ||
  curl -OL https://github.com/prometheus/node_exporter/releases/download/v"$NODE_EXPORTER_VERSION"/node_exporter-"$NODE_EXPORTER_VERSION".linux-"$SYSTEM_ARCH".tar.gz
  echo

  tar xfz node_exporter-*.tar.gz &> /dev/null
  cp node_exporter-"$NODE_EXPORTER_VERSION".linux-"$SYSTEM_ARCH"/node_exporter /usr/local/bin
  chown node_exporter:node_exporter /usr/local/bin/node_exporter

  if [ $LOG_LEVEL -lt 3 ]; then rm -rf node_exporter-"$NODE_EXPORTER_VERSION"*; fi

  printf "node_exporter downloaded\n\n"
}


function init_node_exporter() {
  if [ $LOG_LEVEL -gt 2 ]; then printf "[INFO] Setting node_exporter daemon\n"; fi

  systemctl >/dev/null 2>&1
  # shellcheck disable=SC2181
  if [ $? -eq 0 ]
  then

    cat > /etc/systemd/system/node_exporter.service <<EOM
[Unit]
Description=Node Exporter
Wants=network-online.target
After=network-online.target

[Service]
User=node_exporter
Group=node_exporter
Type=simple
ExecStart=/usr/local/bin/node_exporter \
  --collector.systemd \
  --collector.processes \
  --web.listen-address=:${NODE_EXPORTER_PORT}

[Install]
WantedBy=multi-user.target
EOM


    systemctl daemon-reload
    systemctl enable node_exporter
  else
    update-rc.d node_exporter defaults
    if [ $? -ne 0 ]
    then
      printf "You have to install node_exporter daemon manually!\nSee for instance ruby gem pleaserun https://github.com/jordansissel/pleaserun\n"
      printf "$ pleaserun --user node_exporter --group node_exporter \\\n--install /usr/local/bin/node_exporter --collector.systemd \\\n--collector.processes --web.listen-address=:%s\n\n" "$NODE_EXPORTER_PORT"
    fi
  fi
}


function install_node_exporter() {
  if [ $LOG_LEVEL -gt 3 ]; then echo '[DEBUG] Starting node_exporter installation'; fi
  download_node_exporter
  init_node_exporter
  if [ $LOG_LEVEL -gt 2 ]; then echo '[INFO] node_exporter installed'; fi
}


function download_blackbox_exporter() {
  if [ $LOG_LEVEL -gt 2 ]; then printf "[INFO] Download blackbox_exporter\n"; fi
  useradd --no-create-home --shell /bin/false blackbox_exporter &> /dev/null || grep blackbox_exporter /etc/passwd
  test -f blackbox_exporter-"$BLACKBOX_EXPORTER_VERSION".linux-"$SYSTEM_ARCH".tar.gz ||
  curl -OL https://github.com/prometheus/blackbox_exporter/releases/download/v"$BLACKBOX_EXPORTER_VERSION"/blackbox_exporter-"$BLACKBOX_EXPORTER_VERSION".linux-"$SYSTEM_ARCH".tar.gz
  echo

  tar xfz blackbox_exporter-*.tar.gz &> /dev/null
  cp blackbox_exporter-"$BLACKBOX_EXPORTER_VERSION".linux-"$SYSTEM_ARCH"/blackbox_exporter /usr/local/bin
  chown blackbox_exporter:blackbox_exporter /usr/local/bin/blackbox_exporter

  mkdir /etc/prometheus &> /dev/null
  cp blackbox_exporter-"$BLACKBOX_EXPORTER_VERSION".linux-"$SYSTEM_ARCH"/blackbox.yml /etc/prometheus/
  chown blackbox_exporter:blackbox_exporter /etc/prometheus/blackbox.yml

  if [ $LOG_LEVEL -lt 3 ]; then rm -rf blackbox_exporter-"$BLACKBOX_EXPORTER_VERSION"*; fi

  printf "blackbox_exporter downloaded\n\n"
}


function config_blackbox_exporter() {
  if [ $LOG_LEVEL -gt 3 ]; then printf "[DEBUG] Config blackbox_exporter\n"; fi
  # Set ipv4 as preferred protocol for blackbox_exporter
  sed -i '4i\    http:' /etc/prometheus/blackbox.yml
  sed -i '5i\      preferred_ip_protocol: "ip4"' /etc/prometheus/blackbox.yml
}


function init_blackbox_exporter() {
  if [ $LOG_LEVEL -gt 2 ]; then printf "[INFO] Setting blackbox_exporter daemon\n"; fi

  systemctl >/dev/null 2>&1
  # shellcheck disable=SC2181
  if [ $? -eq 0 ]
  then

    cat > /etc/systemd/system/blackbox_exporter.service <<EOM
[Unit]
Description=Blackbox Exporter
Wants=network-online.target
After=network-online.target

[Service]
User=blackbox_exporter
Group=blackbox_exporter
Type=simple
ExecStart=/usr/local/bin/blackbox_exporter \
  --config.file /etc/prometheus/blackbox.yml \
  --web.listen-address=:${BLACKBOX_EXPORTER_PORT}

[Install]
WantedBy=multi-user.target
EOM


    systemctl daemon-reload
    systemctl enable blackbox_exporter
  else
    update-rc.d blackbox_exporter defaults
    if [ $? -ne 0 ]
    then
      printf "You have to install blackbox_exporter daemon manually!\nSee for instance ruby gem pleaserun https://github.com/jordansissel/pleaserun\n"
      printf "$ pleaserun --user blackbox_exporter --group blackbox_exporter \\\n--install /usr/local/bin/blackbox_exporter --config.file /etc/prometheus/blackbox.yml\\\n--web.listen-address=:%s\n\n" "$BLACKBOX_EXPORTER_PORT"
    fi
  fi
}


function install_blackbox_exporter() {
  if [ $LOG_LEVEL -gt 3 ]; then echo '[DEBUG] Starting blackbox_exporter installation'; fi
  download_blackbox_exporter
  config_blackbox_exporter
  init_blackbox_exporter
  if [ $LOG_LEVEL -gt 2 ]; then echo '[INFO] blackbox_exporter installed'; fi
}


function download_alertmanager() {
  if [ $LOG_LEVEL -gt 2 ]; then printf "[INFO] Download Alertmanager\n"; fi
  useradd --no-create-home --shell /bin/false alertmanager &> /dev/null || grep alertmanager /etc/passwd
  test -f alertmanager-"$ALERTMANAGER_VERSION".linux-"$SYSTEM_ARCH".tar.gz ||
  curl -OL https://github.com/prometheus/alertmanager/releases/download/v"$ALERTMANAGER_VERSION"/alertmanager-"$ALERTMANAGER_VERSION".linux-"$SYSTEM_ARCH".tar.gz
  echo

  tar xfz alertmanager-*.tar.gz &> /dev/null
  cp alertmanager-"$ALERTMANAGER_VERSION".linux-"$SYSTEM_ARCH"/alertmanager /usr/local/bin
  chown alertmanager:alertmanager /usr/local/bin/alertmanager

  if [ $LOG_LEVEL -lt 3 ]; then rm -rf alertmanager-"$ALERTMANAGER_VERSION"*; fi

  printf "Alertmanager downloaded\n\n"
}


function set_alertmanager_folders() {
  mkdir /etc/prometheus &> /dev/null
  mkdir -p /var/lib/alertmanager &> /dev/null

  chown alertmanager:alertmanager /var/lib/alertmanager &> /dev/null
  if [ $LOG_LEVEL -gt 3 ]
  then
    printf "Alertmanager directories:\n"
    ls -all /var/lib/ | grep alertmanager
    echo
  fi
}


function config_alertmanager() {
  if [ $LOG_LEVEL -gt 3 ]; then printf "[DEBUG] Config Alertmanager\n"; fi

  cat > /etc/prometheus/alertmanager.yml <<EOM
global:
  smtp_from: $ALERT_EMAIL_SMTP_FROM
  smtp_smarthost: $ALERT_EMAIL_SMTP_HOSTNAME_AND_PORT
  smtp_auth_username: $ALERT_EMAIL_SMTP_USER
  smtp_auth_password: $ALERT_EMAIL_SMTP_PASS
route:
  group_by: ['alertname']
  # How long to initially wait to send a notification for a group
  # of alerts. Allows to wait for an inhibiting alert to arrive or collect
  # more initial alerts for the same group. (Usually ~0s to few minutes.)
  group_wait: 3s
  # How long to wait before sending a notification about new alerts that
  # are added to a group of alerts for which an initial notification has
  # already been sent. (Usually ~5m or more.)
  group_interval: 5s
  # How long to wait before sending a notification again if it has already
  # been sent successfully for an alert. (Usually ~3h or more).
  repeat_interval: 1h
  receiver: 'alert.services'
receivers:
- name: 'alert.services'
  email_configs:
    - to: $ALERT_EMAIL_TO
  webhook_configs:
    - url: '$ALERT_WEBHOOK_URL'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
EOM

  chown alertmanager:alertmanager /etc/prometheus/alertmanager.yml &> /dev/null
}


function config_alert_rules() {
  if [ $LOG_LEVEL -gt 3 ]; then printf "[DEBUG] Config Alert Rules\n"; fi

  cat > /etc/prometheus/alert.rules.yml <<EOM
groups:
- name: alert.rules
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
      severity: "critical"
    annotations:
      summary: "Endpoint {{ \$labels.instance }} down"
      description: "{{ \$labels.instance }} of job {{ \$labels.job }} has been down for more than 5 minutes."
  - alert: HTTPProbeFailed
    expr: probe_success == 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: HTTP probe failed (instance {{ \$labels.instance }})
      description: "Probe failed\n  VALUE = {{ \$value }}\n  LABELS = {{ \$labels }}"
EOM
}


function init_alertmanager() {
  if [ $LOG_LEVEL -gt 2 ]; then printf "[INFO] Setting Alertmanager daemon\n"; fi

  systemctl >/dev/null 2>&1
  # shellcheck disable=SC2181
  if [ $? -eq 0 ]
  then

    cat > /etc/systemd/system/alertmanager.service <<EOM
[Unit]
Description=Prometheus Altermanager
Wants=network-online.target
After=network-online.target

[Service]
User=alertmanager
Group=alertmanager
Type=simple
ExecStart=/usr/local/bin/alertmanager \
  --config.file /etc/prometheus/alertmanager.yml \
  --cluster.listen-address= \
  --storage.path /var/lib/alertmanager/ \
  --web.listen-address=:${ALERTMANAGER_PORT}

[Install]
WantedBy=multi-user.target
EOM


    systemctl daemon-reload
    systemctl enable alertmanager
  else
    update-rc.d alertmanager defaults
    if [ $? -ne 0 ]
    then
      printf "You have to install alertmanager daemon manually!\nSee for instance ruby gem pleaserun https://github.com/jordansissel/pleaserun\n"
      printf "$ pleaserun --user alertmanager --group alertmanager \\\n--install /usr/local/bin/alertmanager --config.file /etc/prometheus/alertmanager.yml\\\n--web.listen-address=:%s\n\n" "$ALERTMANAGER_PORT"
    fi
  fi
}


function install_alertmanager() {
  if [ $LOG_LEVEL -gt 3 ]; then echo '[DEBUG] Starting alertmanager installation'; fi
  download_alertmanager
  set_alertmanager_folders
  config_alertmanager
  config_alert_rules
  init_alertmanager
  if [ $LOG_LEVEL -gt 2 ]; then echo '[INFO] Alertmanager installed'; fi
}


function download_shell2http() {
  if [ $LOG_LEVEL -gt 2 ]; then printf "[INFO] Download shell2http\n"; fi
  useradd --no-create-home --shell /bin/false shell2http &> /dev/null || grep shell2http /etc/passwd
  test -f shell2http_"$SHELL2HTTP_VERSION"_linux_"$SYSTEM_ARCH".tar.gz ||
  curl -OL https://github.com/msoap/shell2http/releases/download/v"$SHELL2HTTP_VERSION"/shell2http_"$SHELL2HTTP_VERSION"_linux_"$SYSTEM_ARCH".tar.gz
  echo

  tar xfz shell2http_*.tar.gz shell2http &> /dev/null
  cp shell2http /usr/local/bin
  chown shell2http:shell2http /usr/local/bin/shell2http

  if [ $LOG_LEVEL -lt 3 ]; then rm -rf shell2http*; fi

  printf "shell2http downloaded\n\n"
}


function config_shell2http() {
  if [ $LOG_LEVEL -gt 2 ]; then printf "[INFO] Config shell2http\n"; fi

  if [ $LOG_LEVEL -gt 3 ]; then printf "[DEBUG] Storing actual env to be accessible by shell2http on further alerts\n"; fi

  mkdir /etc/prometheus &> /dev/null
  cp .env /etc/prometheus/.env.shell2http
  touch /etc/prometheus/.tmp.shell2http

  chown shell2http:shell2http /etc/prometheus/.env.shell2http &> /dev/null
  chown shell2http:shell2http /etc/prometheus/.tmp.shell2http &> /dev/null

  if [ $LOG_LEVEL -gt 3 ]; then printf "[DEBUG] Prepare script for notification by shell2http\n"; fi
  cat > /etc/prometheus/notify_services.sh << EOM
#!/bin/bash
ALERT_TMP_FILE="/etc/prometheus/.tmp.shell2http"
cat > \$ALERT_TMP_FILE

eval "\$(/usr/local/bin/shdotenv -e /etc/prometheus/.env.shell2http)"

export title="Status: \$(jq -r '.status' \$ALERT_TMP_FILE) |
Alert: \$(jq -r '.commonLabels.alertname' \$ALERT_TMP_FILE) |
Severity: \$(jq -r '.commonLabels.severity' \$ALERT_TMP_FILE)"

export msg="Instance: \$(jq -r '.commonLabels.instance' \$ALERT_TMP_FILE) |
Description: \$(jq -r '.commonAnnotations.description' \$ALERT_TMP_FILE) |
Summary: \$(jq -r '.commonAnnotations.summary' \$ALERT_TMP_FILE)"

eval "set -- \$NOTIFY_SERVICES"
while [ \$# -gt 0 ]; do
  /usr/local/bin/pingme "\$1" \
  --title "\$title" \
  --msg "\$msg"
  shift
done
EOM

  chmod 755 /etc/prometheus/notify_services.sh
  chown shell2http:shell2http /etc/prometheus/notify_services.sh &> /dev/null
}


function init_shell2http() {
  if [ $LOG_LEVEL -gt 2 ]; then printf "[INFO] Setting shell2http daemon\n"; fi

  systemctl >/dev/null 2>&1
  # shellcheck disable=SC2181
  if [ $? -eq 0 ]
  then

    cat > /etc/systemd/system/shell2http.service <<EOM
[Unit]
Description=shell2http
Wants=network-online.target
After=network-online.target

[Service]
User=shell2http
Group=shell2http
Type=simple
ExecStart=/usr/local/bin/shell2http \
  -port=${SHELL2HTTP_PORT} -cgi /notify '/etc/prometheus/notify_services.sh'

[Install]
WantedBy=multi-user.target
EOM


    systemctl daemon-reload
    systemctl enable shell2http
  else
    update-rc.d shell2http defaults
    if [ $? -ne 0 ]
    then
      printf "You have to install shell2http daemon manually!\nSee for instance ruby gem pleaserun https://github.com/jordansissel/pleaserun\n"
      printf "$ pleaserun --user shell2http --group shell2http \\\n--install /usr/local/bin/shell2http -port=%s -cgi /notify '/etc/prometheus/notify_services.sh'\n\n" "$SHELL2HTTP_PORT"
    fi
  fi
}


function install_shell2http() {
  if [ $LOG_LEVEL -gt 3 ]; then echo '[DEBUG] Starting shell2http installation'; fi
  download_shell2http
  config_shell2http
  init_shell2http
  if [ $LOG_LEVEL -gt 2 ]; then echo '[INFO] shell2http installed'; fi
}


function download_pingme() {
  if [ "$SYSTEM_ARCH" = "amd64" ]; then PINGME_SYSTEM_ARCH="x86_64"; else PINGME_SYSTEM_ARCH=$SYSTEM_ARCH; fi

  if [ $LOG_LEVEL -gt 2 ]; then printf "[INFO] Download PingMe CLI\n"; fi
  useradd --no-create-home --shell /bin/false pingme &> /dev/null || grep pingme /etc/passwd
  test -f pingme_Linux_"$PINGME_SYSTEM_ARCH".tar.gz ||
  curl -OL https://github.com/kha7iq/pingme/releases/download/v"$PINGME_VERSION"/pingme_Linux_"$PINGME_SYSTEM_ARCH".tar.gz
  echo

  tar xfz pingme_*.tar.gz pingme &> /dev/null
  cp pingme /usr/local/bin
  chown pingme:pingme /usr/local/bin/pingme

  if [ $LOG_LEVEL -lt 3 ]; then rm -rf pingme*; fi

  printf "PingMe CLI downloaded\n\n"
}


function install_pingme() {
  if [ $LOG_LEVEL -gt 3 ]; then echo '[DEBUG] Starting PingMe CLI installation'; fi
  download_pingme
  if [ $LOG_LEVEL -gt 2 ]; then echo '[INFO] PingMe CLI installed'; fi
}


function set_prometheus_folders() {
  mkdir /etc/prometheus &> /dev/null
  mkdir /var/lib/prometheus &> /dev/null

  chown prometheus:prometheus /etc/prometheus &> /dev/null
  chown prometheus:prometheus /var/lib/prometheus &> /dev/null
  if [ $LOG_LEVEL -gt 3 ]
  then
    ls /etc | grep prometheus | awk '{printf "Directories %s:\n", $1}'
    ls -all /etc | grep prometheus
    ls -all /var/lib/ | grep prometheus
    echo
  fi
}


function download_prometheus() {
  if [ $LOG_LEVEL -gt 2 ]; then printf "[INFO] Download prometheus\n"; fi
  useradd --no-create-home --shell /usr/sbin/nologin prometheus &> /dev/null || grep prometheus /etc/passwd
  set_prometheus_folders
  test -f prometheus-"$PROMETHEUS_VERSION".linux-"$SYSTEM_ARCH".tar.gz ||
  curl -OL https://github.com/prometheus/prometheus/releases/download/v"$PROMETHEUS_VERSION"/prometheus-"$PROMETHEUS_VERSION".linux-"$SYSTEM_ARCH".tar.gz
  echo

  tar xfz prometheus-*.tar.gz &> /dev/null
  cp prometheus-"$PROMETHEUS_VERSION".linux-"$SYSTEM_ARCH"/prometheus /usr/local/bin
  cp prometheus-"$PROMETHEUS_VERSION".linux-"$SYSTEM_ARCH"/promtool /usr/local/bin
  chown prometheus:prometheus /usr/local/bin/prometheus
  chown prometheus:prometheus /usr/local/bin/promtool

  cp -r prometheus-"$PROMETHEUS_VERSION".linux-"$SYSTEM_ARCH"/consoles /etc/prometheus
  cp -r prometheus-"$PROMETHEUS_VERSION".linux-"$SYSTEM_ARCH"/console_libraries /etc/prometheus
  chown -R prometheus:prometheus /etc/prometheus/consoles
  chown -R prometheus:prometheus /etc/prometheus/console_libraries

  if [ $LOG_LEVEL -lt 3 ]; then rm -rf prometheus-"$PROMETHEUS_VERSION"*; fi

  printf "Prometheus downloaded\n\n"
}


function config_prometheus() {
  if [ $LOG_LEVEL -gt 3 ]; then printf "[DEBUG] Config prometheus\n"; fi

  cat > /etc/prometheus/prometheus.yml <<EOM
global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - alert.rules.yml

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['localhost:${ALERTMANAGER_PORT}']

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:${PROMETHEUS_PORT}']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:${NODE_EXPORTER_PORT}']

  - job_name: "http_probe"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
     - targets: [$BLACKBOX_URL_TO_PROBE]
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:${BLACKBOX_EXPORTER_PORT}
EOM

  chown prometheus:prometheus /etc/prometheus/prometheus.yml &> /dev/null
}


function init_prometheus() {
  if [ $LOG_LEVEL -gt 2 ]; then printf "[INFO] Setting prometheus daemon\n"; fi
  systemctl >/dev/null 2>&1
  # shellcheck disable=SC2181
  if [ $? -eq 0 ]
  then

    cat > /etc/systemd/system/prometheus.service <<EOM
[Unit]
  Description=Prometheus Monitoring
  Wants=network-online.target
  After=network-online.target


[Service]
  User=prometheus
  Group=prometheus
  Type=simple
  ExecStart=/usr/local/bin/prometheus \
  --config.file /etc/prometheus/prometheus.yml \
  --storage.tsdb.path /var/lib/prometheus/ \
  --storage.tsdb.no-lockfile \
  --web.console.templates=/etc/prometheus/consoles \
  --web.console.libraries=/etc/prometheus/console_libraries \
  --web.listen-address=:${PROMETHEUS_PORT}
  ExecReload=/bin/kill -HUP ${MAINPID}

[Install]
  WantedBy=multi-user.target
EOM

    systemctl daemon-reload
    systemctl enable prometheus
  else
    update-rc.d prometheus defaults
    if [ $? -ne 0 ]
    then
      printf "You have to install and start prometheus daemon manually!\nSee for instance ruby gem pleaserun https://github.com/jordansissel/pleaserun\n"
      printf "$ pleaserun --user prometheus --group prometheus --install /usr/local/bin/prometheus --config.file /etc/prometheus/prometheus.yml --storage.tsdb.path /var/lib/prometheus/ --storage.tsdb.no-lockfile --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries --web.listen-address=:%s\n\n" "$PROMETHEUS_PORT"
    fi
  fi
}


function install_prometheus() {
  if [ $LOG_LEVEL -gt 3 ]; then echo '[DEBUG] Starting prometheus installation'; fi
  download_prometheus
  config_prometheus
  init_prometheus
  if [ $LOG_LEVEL -gt 2 ]; then echo '[INFO] prometheus installed'; fi
}


function install_apps() {
  if $NODE_TRIGGER; then install_node_exporter; fi
  if $BLACKBOX_TRIGGER; then install_blackbox_exporter; fi
  if $ALERTMANAGER_TRIGGER; then install_alertmanager; fi
  if $SHELL2HTTP_TRIGGER; then install_shell2http; fi
  if $PINGME_TRIGGER; then install_pingme; fi
  if $PROMETHEUS_TRIGGER; then install_prometheus; fi
}


function start_apps() {
  if $NODE_TRIGGER; then service node_exporter start; fi
  if $BLACKBOX_TRIGGER; then service blackbox_exporter start; fi
  if $ALERTMANAGER_TRIGGER; then service alertmanager start; fi
  if $SHELL2HTTP_TRIGGER; then service shell2http start; fi
  if $PROMETHEUS_TRIGGER; then service prometheus start; fi
}


function stop_apps() {
  if $NODE_TRIGGER; then service node_exporter stop; fi
  if $BLACKBOX_TRIGGER; then service blackbox_exporter stop; fi
  if $ALERTMANAGER_TRIGGER; then service alertmanager stop; fi
  if $SHELL2HTTP_TRIGGER; then service shell2http stop; fi
  if $PROMETHEUS_TRIGGER; then service prometheus stop; fi
}


function get_node_status() {
  service node_exporter status | awk 'NR==3 {printf "Status of node_exporter: %s\n", $2}'
}


function get_blackbox_status() {
  service blackbox_exporter status | awk 'NR==3 {printf "Status of blackbox_exporter: %s\n", $2}'
}


function get_alertmanager_status() {
  service alertmanager status | awk 'NR==3 {printf "Status of Alertmanager: %s\n", $2}'
}


function get_shell2http_status() {
  service shell2http status | awk 'NR==3 {printf "Status of CGI SHELL2HTTP API: %s\n", $2}'
}


function get_pingme_status() {
  test -f /usr/local/bin/pingme && printf "Status of PingMe CLI: installed (OK)\n"
}


function get_prometheus_status() {
  service prometheus status | awk 'NR==3 {printf "Status of Prometheus: %s\n", $2}'
}


function get_status() {
  if $NODE_TRIGGER; then get_node_status; fi
  if $BLACKBOX_TRIGGER; then get_blackbox_status; fi
  if $ALERTMANAGER_TRIGGER; then get_alertmanager_status; fi
  if $SHELL2HTTP_TRIGGER; then get_shell2http_status; fi
  if $PINGME_TRIGGER; then get_pingme_status; fi
  if $PROMETHEUS_TRIGGER; then get_prometheus_status; fi
  echo
}


function remove_node_exporter() {
  rm /usr/local/bin/node_exporter

  deluser --remove-home node_exporter

  systemctl >/dev/null 2>&1
  # shellcheck disable=SC2181
  if [ $? -eq 0 ]
  then
    rm /etc/systemd/system/node_exporter.service
    systemctl daemon-reload
  else
    rm /etc/init.d/node_exporter
    rm /etc/default/node_exporter
    update-rc.d node_exporter remove
  fi
}


function remove_blackbox_exporter() {
  rm /usr/local/bin/blackbox_exporter

  deluser --remove-home blackbox_exporter

  systemctl >/dev/null 2>&1
  # shellcheck disable=SC2181
  if [ $? -eq 0 ]
  then
    rm /etc/systemd/system/blackbox_exporter.service
    systemctl daemon-reload
  else
    rm /etc/init.d/blackbox_exporter
    rm /etc/default/blackbox_exporter
    update-rc.d blackbox_exporter remove
  fi
}


function remove_alertmanager() {
  rm /usr/local/bin/alertmanager

  deluser --remove-home alertmanager

  systemctl >/dev/null 2>&1
  # shellcheck disable=SC2181
  if [ $? -eq 0 ]
  then
    rm /etc/systemd/system/alertmanager.service
    systemctl daemon-reload
  else
    rm /etc/init.d/alertmanager
    rm /etc/default/alertmanager
    update-rc.d alertmanager remove
  fi
}


function remove_shell2http() {
  rm /usr/local/bin/shell2http
  rm /etc/prometheus/notify_services.sh
  rm /etc/prometheus/.env.shell2http
  rm /etc/prometheus/.tmp.shell2http

  deluser --remove-home shell2http

  systemctl >/dev/null 2>&1
  # shellcheck disable=SC2181
  if [ $? -eq 0 ]
  then
    rm /etc/systemd/system/shell2http.service
    systemctl daemon-reload
  else
    rm /etc/init.d/shell2http
    rm /etc/default/shell2http
    update-rc.d shell2http remove
  fi
}


function remove_pingme() {
  rm /usr/local/bin/pingme

  deluser --remove-home pingme
}


function remove_prometheus() {
  rm /usr/local/bin/prometheus
  rm /usr/local/bin/promtool
  rm -rf /etc/prometheus
  rm -rf /var/lib/prometheus/

  deluser --remove-home prometheus

  systemctl >/dev/null 2>&1
  # shellcheck disable=SC2181
  if [ $? -eq 0 ]
  then
    rm /etc/systemd/system/prometheus.service
    systemctl daemon-reload
  else
    rm /etc/init.d/prometheus
    rm /etc/default/prometheus
    update-rc.d prometheus remove
  fi
}


function remove_apps() {
  if $NODE_TRIGGER; then remove_node_exporter; fi
  if $BLACKBOX_TRIGGER; then remove_blackbox_exporter; fi
  if $ALERTMANAGER_TRIGGER; then remove_alertmanager; fi
  if $SHELL2HTTP_TRIGGER; then remove_shell2http; fi
  if $PINGME_TRIGGER; then remove_pingme; fi
  if $PROMETHEUS_TRIGGER; then remove_prometheus; fi
}


function list_used_ports() {
  if ! command -v lsof &> /dev/null
  then
    echo "Command lsof could not be found, install it first!"
    echo
    exit
  else
    printf "Actual ports used on this machine:\n"
    lsof -n -i -P | grep LISTEN
    echo
  fi
}


function retrieve_env_datas() {
  # Retrieve .env values with abstraction of special characters
  if [ $LOG_LEVEL -gt 3 ]; then printf "[DEBUG] Download shdotenv if needed\n"; fi

  test -f /usr/local/bin/shdotenv || curl -OL https://github.com/matbgn/prommanager/raw/master/lib/shdotenv &> /dev/null

  cp shdotenv /usr/local/bin &> /dev/null
  chmod 755 /usr/local/bin/shdotenv
  rm shdotenv &> /dev/null

  if [ $LOG_LEVEL -gt 3 ]; then echo '[DEBUG] shdotenv installed'; fi

  if [ $LOG_LEVEL -gt 2 ]; then echo '[INFO] Load env files'; fi

  eval "$(/usr/local/bin/shdotenv -e .env)"
  # Compose additional env var based on .env file
  ALERT_WEBHOOK_URL="http://localhost:$SHELL2HTTP_PORT/notify"

  # Retrieve versions from .versions file in form of:
  # NODE_EXPORTER_VERSION=1.3.1
  # PROMETHEUS_VERSION=2.33.5
  eval "$(/usr/local/bin/shdotenv -e .versions)"
}


# shellcheck disable=SC2120
function main() {
  printf 'Selected architecture is %s\n\n' "$SYSTEM_ARCH"

  if $KILL_APPS; then
    stop_apps
    sleep 1
    if (! $STATUS_APPS); then get_status; fi
  fi

  if $REMOVE_APPS; then
    remove_apps
  fi

  update_versions

  if $UPDATE_CONFIGS; then
    config_alertmanager
    config_alert_rules
    config_shell2http
    config_prometheus
  fi

  if $DISPLAY_VERSIONS; then
    display_versions
  fi

  if $INSTALL; then
    install_apps
  fi

  if $EXECUTE; then
    start_apps
    sleep 1
    if (! $STATUS_APPS); then get_status; fi
  fi

  if $STATUS_APPS; then
    get_status
  fi
}


echo "$MOTD"
check_root_rights
echo

if [[ ${#} -eq 0 ]]; then
   usage
fi

flags "$@"
retrieve_env_datas
# shellcheck disable=SC2119
main
